services:
  camunda:
    image: camunda/camunda-bpm-platform:run-latest
    container_name: camunda
    ports:
      - "8080:8080"
    volumes:
      - ./processos:/camunda/configuration/resources
    networks:
      - camunda-net

  worker:
    build: ./worker
    container_name: camunda-worker
    depends_on:
      - camunda
    networks:
      - camunda-net

networks:
  camunda-net:
    driver: bridge
