version: '3.8'

services:
  camunda:
    image: camunda/camunda-bpm-platform:run-latest
    container_name: camunda
    ports:
      - "8080:8080"
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./processos:/camunda/configuration/resources
      - ./forms:/camunda/configuration/resources
